DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "My New Hugo i18n Site"
    languageName = "English"
    weight = 1
  [languages.el-gr]
    title = "Η Νεα μου Ιστιοσελιδα"
    languageName = "Greek"
    weight = 2
